(function (factory) {
  if (typeof module !== "undefined" && module.exports) {
    module.exports = factory();
    return;
  }

  const root = typeof globalThis !== "undefined" ? globalThis : self;
  root.SongTrackerParser = factory();
})(function () {

  const NOISE_PATTERNS = [
    /\bofficial\s+(music\s+)?video\b/gi,
    /\bofficial\s+audio\b/gi,
    /\baudio\b/gi,
    /\bvisualizer\b/gi,
    /\bmv\b/gi,
    /\bhd\b/gi,
    /\b4k\b/gi,
    /\bvideo\s+clip\b/gi,
    /\bperformance\s+video\b/gi,
    /\btopic\b/gi,
    /\bfull\s+album\b/gi
  ];

  const MULTI_TRACK_PATTERNS = [
    /\bmix\b/i,
    /\bplaylist\b/i,
    /\bcompilation\b/i,
    /\blive stream\b/i,
    /\bradio\b/i,
    /\bset\b/i,
    /\bmashup\b/i
  ];

  const STRONG_NON_MUSIC_PATTERNS = [
    /\bvs\b/i,
    /\bgrand\s+finals?\b/i,
    /\bsemi-?finals?\b/i,
    /\bquarter-?finals?\b/i,
    /\bhighlights?\b/i,
    /\bmatch\b/i,
    /\bgameplay\b/i,
    /\btournament\b/i,
    /\brecap\b/i,
    /\breaction\b/i,
    /\binterview\b/i,
    /\bepisode\b/i,
    /\btrailer\b/i,
    /\bnews\b/i,
    /\bpreview\b/i,
    /\bstandings?\b/i,
    /\bwatch\s+party\b/i
  ];

  const MUSIC_CHANNEL_PATTERNS = [
    /\bmusic\b/i,
    /\brecords?\b/i,
    /\btopic\b/i,
    /\bvevo\b/i,
    /\brap\b/i
  ];

  const CHANNEL_PENALTY_PATTERNS = [
    /\btv\b/i,
    /\bmedia\b/i,
    /\bchannel\b/i,
    /\bentertainment\b/i,
    /\bstudio\b/i,
    /\bnetwork\b/i,
    /\bproductions?\b/i
  ];

  const STRONG_MUSIC_DESCRIPTION_PATTERNS = [
    /provided to youtube by/i,
    /auto-generated by youtube/i,
    /\breleased on:\b/i,
    /\bcomposer\b/i,
    /\bcomposed by\b/i,
    /\blyricist\b/i,
    /\blyrics?\b/i,
    /\bwritten by\b/i,
    /\barranged by\b/i,
    /\barranger\b/i,
    /\bproducer\b/i,
    /\bproduced by\b/i,
    /\bperformed by\b/i,
    /\boriginal song\b/i,
    /\bvocals?\b/i,
    /\bartist:\b/i,
    /\balbum:\b/i,
    /作词/,
    /作曲/,
    /编曲/,
    /词曲/,
    /填词/,
    /谱曲/,
    /制作人/,
    /监制/,
    /出品/,
    /演唱/,
    /原唱/,
    /翻唱/,
    /歌词/,
    /动态歌词/,
    /拼音歌词/,
    /字幕/,
    /专辑/,
    /发行/,
    /音乐制作/,
    /混音/,
    /母带/
  ];

  const STRONG_MUSIC_TITLE_PATTERNS = [
    /\blyric\s+video\b/i,
    /\blyrics?\b/i,
    /\bpinyin\s+lyrics?\b/i,
    /\bofficial\s+(music\s+)?video\b/i,
    /\bofficial\s+audio\b/i,
    /\bvisualizer\b/i,
    /\bremix\b/i,
    /\bcover\b/i,
    /\blive\b/i,
    /\bmusic\s+video\b/i,
    /\bofficial\s+lyrics?\b/i,
    /\bpiano\s+cover\b/i,
    /\bguitar\s+cover\b/i,
    /\bdrum\s+cover\b/i,
    /\bdance\s+practice\b/i,
    /\bperformance\s+video\b/i,
    /\bprod\.?\b/i,
    /\bfeat\.?\b/i,
    /\bft\.?\b/i,
    /\bsped\s*up\b/i,
    /\bslowed\b/i,
    /\breverb\b/i,
    /\bnightcore\b/i,
    /\b8d\s+audio\b/i,
    /\bkaraoke\b/i,
    /\binstrumental\b/i,
    /\bacoustic\b/i,
    /\bost\b/i,
    /\bsoundtrack\b/i,
    /\btheme song\b/i,
    /\boriginal soundtrack\b/i,
    /\bdynamic\s+lyrics?\b/i,
    /动态歌词/i,
    /拼音歌词/i,
    /歌词/i,
    /翻唱/i,
    /改编/i,
    /原唱/i,
    /作词/i,
    /作曲/i,
    /编曲/i,
    /演唱/i,
    /音乐录影带/i,
    /音乐视频/i,
    /纯音乐/i,
    /伴奏/i,
    /加速/i,
    /慢速/i,
    /现场/i,
    /混音/i,
    /母带/i,
    /主题曲/i,
    /片尾曲/i,
    /片头曲/i,
    /插曲/i
  ];

  const AMBIGUOUS_MUSIC_WORD_PATTERNS = [
    /\bcover\b/i,
    /\bdemo\b/i,
    /\blive\b/i,
    /\bperformance\b/i,
    /\bversion\b/i,
    /\bacoustic\b/i,
    /\binstrumental\b/i,
    /\bkaraoke\b/i,
    /\bsession\b/i,
    /\bunplugged\b/i,
    /翻唱/i,
    /现场/i,
    /版本/i,
    /演示/i,
    /试唱/i
  ];

  const FALSE_POSITIVE_MUSIC_PHRASES = [
    /\bcover your\b/i,
    /\bdemo (this|that|the|a|an)\b/i,
    /\blive stream\b/i,
    /\blive update\b/i,
    /\bperformance review\b/i,
    /\bcover letter\b/i,
    /\bcover page\b/i,
    /\bdemo app\b/i,
    /\bdemo project\b/i,
    /\bdemo video\b/i
  ];

  function normalizeWhitespace(value) {
    return (value || "").replace(/\s+/g, " ").trim();
  }

  function stripNoise(value) {
    let result = value || "";

    result = result.replace(/\[[^\]]*\]/g, " ");
    result = result.replace(/【[^】]*】/g, " ");
    result = result.replace(/\((?![^)]*(feat|ft\.?|remaster|version|live|acoustic|remix|cover))[^)]*\)/gi, " ");
    result = result.replace(/（(?![^）]*(feat|ft\.?|remaster|version|live|acoustic|remix|cover))[^）]*）/gi, " ");

    for (const pattern of NOISE_PATTERNS) {
      result = result.replace(pattern, " ");
    }

    result = result.replace(/[_~]+/g, " ");
    result = result.replace(/\s*[|:]+\s*/g, " - ");

    return normalizeWhitespace(result);
  }

  function splitArtistAndTitle(title, channelName, rawTitle) {
    const cleanedTitle = stripNoise(title);
    const bracketMatch = cleanedTitle.match(/^(.*?)\s*[<\[{(]?\u300a([^\u300b]+)\u300b[>\]})]?\s*$/);
    if (bracketMatch) {
      const artist = cleanArtistList(bracketMatch[1]);
      const songTitle = normalizeWhitespace(bracketMatch[2]);
      if (artist && songTitle) {
        return { artist, title: songTitle, strategy: "cjk-title-brackets" };
      }
    }

    const separators = [" - ", " | ", ": "];
    for (const separator of separators) {
      if (!cleanedTitle.includes(separator)) continue;
      const [left, ...rest] = cleanedTitle.split(separator);
      const artist = cleanArtistList(left);
      const songTitle = normalizeWhitespace(rest.join(separator));
      if (artist && songTitle) {
        return { artist, title: songTitle, strategy: "title-separator" };
      }
    }

    const quotedTitleMatch = cleanedTitle.match(/^(.*?)["'\u201c\u201d\u2018\u2019]([^"'\u201c\u201d\u2018\u2019]+)["'\u201c\u201d\u2018\u2019]\s*$/);
    if (quotedTitleMatch) {
      const artist = cleanArtistList(quotedTitleMatch[1]);
      const songTitle = normalizeWhitespace(quotedTitleMatch[2]);
      if (artist && songTitle) {
        return { artist, title: songTitle, strategy: "quoted-title" };
      }
    }

    if (isLikelyArtistChannel(channelName) && hasArtistChannelSupport(channelName, rawTitle || cleanedTitle, "")) {
      return {
        artist: normalizeWhitespace(channelName.replace(/\s+-\s+topic$/i, "")),
        title: cleanedTitle,
        strategy: "artist-channel-fallback"
      };
    }

    return {
      artist: "",
      title: cleanedTitle,
      strategy: "title-only"
    };
  }

  function cleanArtistList(value) {
    let result = normalizeWhitespace(value);
    if (!result) return "";

    result = result.replace(/\s*[xX\u00d7\u2718]\s*/g, " x ");
    result = result.replace(/\s*(feat\.?|ft\.?)\s*/gi, " feat. ");
    result = result.replace(/\s*&\s*/g, " & ");
    result = result.replace(/\s*,\s*/g, ", ");
    result = result.replace(/\s+\/\s+/g, " / ");
    result = result.replace(/\s*[-]+\s*$/, "");

    return normalizeWhitespace(result);
  }

  function isLikelyArtistChannel(channelName) {
    const name = normalizeWhitespace(channelName.replace(/\s+-\s+topic$/i, ""));
    if (!name) return false;
    if (/\s-\s*topic$/i.test(channelName)) return true;
    if (MUSIC_CHANNEL_PATTERNS.some((pattern) => pattern.test(name))) return true;
    if (CHANNEL_PENALTY_PATTERNS.some((pattern) => pattern.test(name))) return false;
    return false;
  }

  function isMusicChannel(channelName) {
    return MUSIC_CHANNEL_PATTERNS.some((pattern) => pattern.test(channelName || ""));
  }

  function hasStrongMusicDescription(description) {
    return STRONG_MUSIC_DESCRIPTION_PATTERNS.some((pattern) => pattern.test(description || ""));
  }

  function hasStrongMusicTitle(title) {
    return STRONG_MUSIC_TITLE_PATTERNS.some((pattern) => pattern.test(title || ""));
  }

  function hasAmbiguousMusicWord(title) {
    return AMBIGUOUS_MUSIC_WORD_PATTERNS.some((pattern) => pattern.test(title || ""));
  }

  function hasFalsePositiveMusicPhrase(title) {
    return FALSE_POSITIVE_MUSIC_PHRASES.some((pattern) => pattern.test(title || ""));
  }

  function hasStrongNonMusicSignals(title, channelName, description) {
    const combined = `${title || ""} ${channelName || ""} ${description || ""}`;
    return STRONG_NON_MUSIC_PATTERNS.some((pattern) => pattern.test(combined));
  }

  function detectVariantType(rawTitle, hasSupportingMusicContext) {
    const title = rawTitle || "";
    if (/\bremix\b/i.test(title)) return "remix";
    if ((/\bcover\b/i.test(title) || /翻唱/i.test(title)) && hasSupportingMusicContext) return "cover";
    if (/\blive\b/i.test(title) && hasSupportingMusicContext) return "live";
    if (/\bsped\s*up\b/i.test(title)) return "sped_up";
    if (/\bslowed\b/i.test(title)) return "slowed";
    if (/\blyrics?\b/i.test(title) || /歌词/i.test(title) || /拼音歌词/i.test(title) || /动态歌词/i.test(title)) return "lyrics";
    if (/改编/i.test(title) && hasSupportingMusicContext) return "edit";
    return "";
  }

  function hasArtistChannelSupport(channelName, title, description) {
    return /topic$|vevo$/i.test(channelName || "") || isMusicChannel(channelName) || hasStrongMusicDescription(description) || hasStrongMusicTitle(title);
  }

  function looksMusicLike(title, channelName, description) {
    const hasSeparator = /\s-\s/.test(title || "");
    const hasSongTitleMarkers = /\u300a[^\u300b]+\u300b/.test(title || "") || /["'\u201c\u201d\u2018\u2019]/.test(title || "");
    const musicChannel = isMusicChannel(channelName);

    if (hasStrongMusicDescription(description)) return true;
    if (hasStrongMusicTitle(title)) return true;
    if (musicChannel) return true;
    if (/topic$|vevo$/i.test(channelName || "")) return true;
    if (hasAmbiguousMusicWord(title) && (hasSeparator || hasSongTitleMarkers || musicChannel || hasStrongMusicDescription(description))) {
      return true;
    }
    if (hasSongTitleMarkers) return true;
    if (hasSeparator) return true;
    return false;
  }

  function inferConfidence(input) {
    let score = 0.16;
    const ambiguousMusicWord = hasAmbiguousMusicWord(input.rawTitle || input.title);
    const falsePositivePhrase = hasFalsePositiveMusicPhrase(input.rawTitle || input.title);
    const hasSupportingMusicContext =
      /\s-\s/.test(input.title || "") ||
      /topic$|vevo$/i.test(input.channelName || "") ||
      isMusicChannel(input.channelName || "") ||
      hasStrongMusicDescription(input.description) ||
      /["'\u201c\u201d\u2018\u2019]/.test(input.title || "") ||
      /\u300a[^\u300b]+\u300b/.test(input.title || "");
    const variantType = detectVariantType(input.rawTitle || input.title, hasSupportingMusicContext);

    if (input.isMusicDomain) score += 0.22;
    if (input.parsed.artist) score += 0.18;
    if (input.parsed.title) score += 0.12;
    if (input.parsed.strategy === "title-separator") score += 0.18;
    if (input.parsed.strategy === "cjk-title-brackets") score += 0.25;
    if (input.parsed.strategy === "quoted-title") score += 0.16;
    if (input.parsed.strategy === "artist-channel-fallback") score += 0.08;
    if (input.channelName && /topic$|vevo$/i.test(input.channelName)) score += 0.24;
    if (isMusicChannel(input.channelName)) score += 0.12;
    if (hasStrongMusicDescription(input.description)) score += 0.26;
    if (hasStrongMusicTitle(input.rawTitle || input.title)) score += 0.24;
    if (ambiguousMusicWord && hasSupportingMusicContext && !falsePositivePhrase) score += 0.12;
    if (variantType) score += 0.16;
    if (looksMusicLike(input.rawTitle || input.title, input.channelName, input.description)) score += 0.1;
    if (MULTI_TRACK_PATTERNS.some((pattern) => pattern.test(input.title || "")) && !variantType) score -= 0.35;
    if (hasStrongNonMusicSignals(input.title, input.channelName, input.description) && !variantType) score -= 0.45;
    if (falsePositivePhrase) score -= 0.45;
    if ((input.title || "").length < 2) score -= 0.15;
    if (!input.parsed.artist) score -= 0.1;
    if (!isLikelyArtistChannel(input.channelName) && input.parsed.strategy === "artist-channel-fallback") score -= 0.25;

    return {
      confidence: Math.max(0, Math.min(1, Number(score.toFixed(2)))),
      variantType
    };
  }

  function extractClassifierFeatures(raw) {
    const title = normalizeWhitespace(raw.title);
    const channelName = normalizeWhitespace(raw.channelName);
    const description = normalizeWhitespace(raw.description);
    const parsed = splitArtistAndTitle(title, channelName, raw.title);
    const rawTitle = raw.title || title;
    const titleForSignals = rawTitle || title;
    const titleLower = titleForSignals.toLowerCase();
    const channelLower = channelName.toLowerCase();
    const descriptionLower = description.toLowerCase();
    const hasSupportingMusicContext =
      /\s-\s/.test(title || "") ||
      /topic$|vevo$/i.test(channelName || "") ||
      isMusicChannel(channelName || "") ||
      hasStrongMusicDescription(description) ||
      /["'\u201c\u201d\u2018\u2019]/.test(title || "") ||
      /\u300a[^\u300b]+\u300b/.test(title || "");
    const { confidence, variantType } = inferConfidence({
      title,
      channelName,
      rawTitle,
      description,
      parsed,
      isMusicDomain: raw.sourcePage === "music.youtube.com"
    });

    return {
      title,
      channelName,
      description,
      rawTitle,
      parsed,
      parserConfidence: confidence,
      variantType,
      flags: {
        isMusicDomain: raw.sourcePage === "music.youtube.com",
        hasStrongMusicTitle: hasStrongMusicTitle(titleForSignals),
        hasStrongMusicDescription: hasStrongMusicDescription(description),
        hasAmbiguousMusicWord: hasAmbiguousMusicWord(titleForSignals),
        hasFalsePositiveMusicPhrase: hasFalsePositiveMusicPhrase(titleForSignals),
        hasStrongNonMusicSignals: hasStrongNonMusicSignals(title, channelName, description),
        looksMusicLike: looksMusicLike(titleForSignals, channelName, description),
        isMusicChannel: isMusicChannel(channelName),
        isLikelyArtistChannel: isLikelyArtistChannel(channelName),
        hasSeparator: /\s-\s/.test(title || ""),
        hasQuotes: /["'\u201c\u201d\u2018\u2019]/.test(title || ""),
        hasCjkTitleBrackets: /\u300a[^\u300b]+\u300b/.test(title || ""),
        hasFeat: /\b(feat\.?|ft\.?)\b/i.test(titleForSignals),
        hasRemix: /\bremix\b/i.test(titleForSignals),
        hasCover: /\bcover\b/i.test(titleForSignals) || /缈诲敱/i.test(titleForSignals),
        hasLive: /\blive\b/i.test(titleForSignals) || /鐜板満/i.test(titleForSignals),
        hasLyrics: /\blyrics?\b/i.test(titleForSignals) || /姝岃瘝/i.test(titleForSignals),
        hasTopicSuffix: /topic$/i.test(channelName),
        hasVevoSuffix: /vevo$/i.test(channelName),
        isMultiTrack: MULTI_TRACK_PATTERNS.some((pattern) => pattern.test(titleForSignals))
      },
      stats: {
        titleLength: title.length,
        channelLength: channelName.length,
        descriptionLength: description.length,
        titleTokenCount: title ? title.split(/\s+/).length : 0,
        channelTokenCount: channelName ? channelName.split(/\s+/).length : 0,
        descriptionTokenCount: description ? description.split(/\s+/).length : 0,
        separatorCount: (title.match(/\s-\s/g) || []).length,
        exclamationCount: (title.match(/!/g) || []).length,
        bracketCount: (title.match(/[\[\](){}]/g) || []).length
      },
      text: {
        normalizedTitle: parsed.title,
        normalizedArtist: parsed.artist,
        parsingStrategy: parsed.strategy,
        titleLower,
        channelLower,
        descriptionLower
      }
    };
  }

  function parseVideoMetadata(raw) {
    const features = extractClassifierFeatures(raw);

    return {
      title: features.title,
      channelName: features.channelName,
      normalizedTitle: features.text.normalizedTitle,
      normalizedArtist: features.text.normalizedArtist,
      parsingStrategy: features.text.parsingStrategy,
      variantType: features.variantType,
      confidence: features.parserConfidence,
      isLikelyMusic: features.parserConfidence >= 0.55
    };
  }

  return {
    parseVideoMetadata,
    extractClassifierFeatures
  };
});
